In [10]:
import pandas as pd

In [11]:
# Access metadata from repository
prey = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e')

In [12]:
# Sets max column to none
pd.set_option("display.max.columns", None)

In [13]:
prey

,attribute,description
0,class,taxonomic class of observed organism
1,order,taxonomic order of observed organism
2,family,taxonomic family of observed organism
3,genus,genus name
4,species,full latin binomial name
5,lat,latitude of occurrence record in decimal degrees
6,long,longitude of occurrence record in decimal degrees
7,eventDate,date and time of observation in YYYY-MM-DD HH:...
8,day,day of the month of observation
9,month,month of observation
10,year,observation year
11,institutionCode,institution code provided by GBIF (www.gbif.org)
12,coordinateUncertaintyInMeters,coordinate uncertainty in meters; NA indicate ...
13,basisOfRecord,"type of record provided by GBIF; one of ""HUMAN..."
14,individualCount,number of individuals (if provided) observed f...
15,datasetKey,unique dataset key provided by GBIF
16,bio1,"annual mean temperature (degrees Celsius, x10)"
17,bio10,mean temperature of warmest quarter (degrees C...
18,bio11,mean temperature of coldest quarter (degrees C...
19,bio12,annual precipitation (millimeters (mm))
20,bio13,precipitation of wettest month (mm)
21,bio14,precipitation of driest month (mm)
22,bio15,precipitation seasonality (percent)
23,bio16,precipitation of wettest quarter (mm)
24,bio17,precipitation of driest quarter (mm)
25,bio18,precipitation of warmest quarter (mm)
26,bio19,precipitation of coldest quarter (mm)
27,bio2,"annual mean diurnal range (degrees Celsius, x10)"
28,bio3,isothermality (percent)
29,bio4,"temperature seasonality (degrees Celsius, x100)"
30,bio5,max temperature of warmest month (degrees Cels...
31,bio6,min temperature of coldest month (degrees Cels...
32,bio7,"annual temperature range (degrees Celsius, x10)"
33,bio8,mean temperature of wettest month (degrees Cel...
34,bio9,mean temperature of driest quarter (degrees Ce...
35,dist,distance to the nearest major road (kilometers...
36,dem90_hf,elevation (meters); data from the National Ele...
37,lc_class,landcover classification from the University o...
38,ndvi,the mean normalized difference vegetation inde...
39,notes,all bioX variables are from the WorldClim data...

In [14]:
type(prey)

pandas.core.frame.DataFrame

In [15]:
prey.head()

  attribute                            description
0     class   taxonomic class of observed organism
1     order   taxonomic order of observed organism
2    family  taxonomic family of observed organism
3     genus                             genus name
4   species               full latin binomial name

In [16]:
prey.tail()

   attribute                                        description
35      dist  distance to the nearest major road (kilometers...
36  dem90_hf  elevation (meters); data from the National Ele...
37  lc_class  landcover classification from the University o...
38      ndvi  the mean normalized difference vegetation inde...
39     notes  all bioX variables are from the WorldClim data...

In [17]:
prey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   attribute    40 non-null     object
 1   description  40 non-null     object
dtypes: object(2)
memory usage: 768.0+ bytes

In [18]:
prey.nunique()

attribute      40
description    40
dtype: int64

In [19]:
prey.shape

(40, 2)

In [20]:
prey.columns

Index(['attribute', 'description'], dtype='object')

In [21]:
prey.dtypes

attribute      object
description    object
dtype: object

In [22]:
prey = prey.rename(index={'institutionCode': 'institution_code', 'datasetKey': 'dataset_key'})

In [23]:
prey

,attribute,description
0,class,taxonomic class of observed organism
1,order,taxonomic order of observed organism
2,family,taxonomic family of observed organism
3,genus,genus name
4,species,full latin binomial name
5,lat,latitude of occurrence record in decimal degrees
6,long,longitude of occurrence record in decimal degrees
7,eventDate,date and time of observation in YYYY-MM-DD HH:...
8,day,day of the month of observation
9,month,month of observation
10,year,observation year
11,institutionCode,institution code provided by GBIF (www.gbif.org)
12,coordinateUncertaintyInMeters,coordinate uncertainty in meters; NA indicate ...
13,basisOfRecord,"type of record provided by GBIF; one of ""HUMAN..."
14,individualCount,number of individuals (if provided) observed f...
15,datasetKey,unique dataset key provided by GBIF
16,bio1,"annual mean temperature (degrees Celsius, x10)"
17,bio10,mean temperature of warmest quarter (degrees C...
18,bio11,mean temperature of coldest quarter (degrees C...
19,bio12,annual precipitation (millimeters (mm))
20,bio13,precipitation of wettest month (mm)
21,bio14,precipitation of driest month (mm)
22,bio15,precipitation seasonality (percent)
23,bio16,precipitation of wettest quarter (mm)
24,bio17,precipitation of driest quarter (mm)
25,bio18,precipitation of warmest quarter (mm)
26,bio19,precipitation of coldest quarter (mm)
27,bio2,"annual mean diurnal range (degrees Celsius, x10)"
28,bio3,isothermality (percent)
29,bio4,"temperature seasonality (degrees Celsius, x100)"
30,bio5,max temperature of warmest month (degrees Cels...
31,bio6,min temperature of coldest month (degrees Cels...
32,bio7,"annual temperature range (degrees Celsius, x10)"
33,bio8,mean temperature of wettest month (degrees Cel...
34,bio9,mean temperature of driest quarter (degrees Ce...
35,dist,distance to the nearest major road (kilometers...
36,dem90_hf,elevation (meters); data from the National Ele...
37,lc_class,landcover classification from the University o...
38,ndvi,the mean normalized difference vegetation inde...
39,notes,all bioX variables are from the WorldClim data...